version: 2

sources:
  - name: raw
    database: postgres
    schema: public
    tables:
      - name: fires_raw
        description: Raw fires data from MODIS CSV
      - name: fires_bronze
        description: Bronze layer - validated and cleaned fires data
        schema: bronze
