fires_project:
  outputs:
    default:
      type: postgres
      host: host.docker.internal  
      dbname: postgres 
      user: postgres
      password: postgres
      port: 5432
      schema: public
    dev:
      type: postgres
      host: host.docker.internal  
      dbname: postgres 
      user: postgres
      password: postgres
      port: 5432
      schema: public